### ISSUE TITLE
곡 검색 API 작성

### ISSUE THREAD

**Issue by yejin0718** [Challenge02/HangehaeMusicClub-BE#15]
# Description
곡 검색 API 작성

## Todo
- [ ] Repository 작성
- [ ] Repository 테스트 코드 작성
- [ ] Service 작성
- [ ] Service 테스트 코드 작성
- [ ] Controller 작성
- [ ] Controller 테스트 코드 작성

## Etc
기타사항을 작성해주세요.
