### ISSUE TITLE
CORS 설정

### ISSUE THREAD

**Issue by yanJuicy** [Challenge02/HangehaeMusicClub-BE#29]
# Description
CORS 설정

## Todo
- [ ] WebMvcConfigurer 구현 클래스 작성
- [ ] localhost 프론트 origin 추가
- [ ] github pages origin 추가
