### ISSUE TITLE
검색 API 레포지토리 클래스 작성

### ISSUE THREAD

**Issue by yanJuicy** [Challenge02/HangehaeMusicClub-BE#7]
# Description
설명을 작성해주세요.

## Todo
- [ ] 레포지토리 클래스 작성
- [ ] 페이징 메소드 작성
- [ ] 레포지토리 테스트 코드 작성
